# Generated by Django 3.1.7 on 2021-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_address', models.EmailField(max_length=40)),
                ('subject', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
