# Generated by Django 3.1.7 on 2021-04-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('student_add_data', models.DateField(auto_now_add=True)),
                ('student_address', models.CharField(default='no address', max_length=40)),
                ('local_guardian_name', models.CharField(default='no address', max_length=40)),
                ('local_guardian_address', models.CharField(default='no address', max_length=40)),
                ('local_guardian_phone', models.CharField(default='no address', max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
