# Generated by Django 3.1.7 on 2021-04-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_auto_20210408_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
