# Generated by Django 3.1.7 on 2021-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_students_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_address', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
