# Generated by Django 3.1.7 on 2021-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_mailbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='sent_address',
            field=models.EmailField(max_length=40),
        ),
    ]
