# Generated by Django 3.1.7 on 2021-04-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0005_auto_20210409_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailbox',
        ),
    ]
